# Generated by Django 5.1 on 2024-09-02 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_post_pp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pp',
            field=models.ImageField(upload_to=''),
        ),
    ]
